/**
 * [INPUT]: 依赖 types 的 MaterialId/MaterialDefinition 与 schema 的 MATERIAL_SCHEMA
 * [OUTPUT]: 对外提供 MATERIAL_REGISTRY（materialId → MaterialDefinition）与 getMaterialDefinition
 * [POS]: remotion-kit/src/materials 的元数据注册层；catalog 的 engine=three effects 条目从同一来源生成
 * [PROTOCOL]: 变更时更新此头部，然后检查 README.md
 */
import { MATERIAL_SCHEMA } from "./schema";
import type { MaterialDefinition, MaterialId, MaterialRegistry } from "./types";

export const MATERIAL_REGISTRY: MaterialRegistry = {
  glitch: {
    id: "glitch",
    label: "Glitch",
    category: "post",
    description: "横向 tearing、RGB split 与噪声 burst；突发型效果使用确定性时间窗口。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.glitch,
  },
  crt: {
    id: "crt",
    label: "CRT",
    category: "post",
    description: "barrel、滚动刷新带、行级轻抖、scanline、RGB aperture 与微闪的老式显像管效果。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.crt,
  },
  vintage: {
    id: "vintage",
    label: "Vintage",
    category: "post",
    description: "gate weave、grain、scratch、dust、light leak 与 faded print 的胶片效果。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.vintage,
  },
  vhs: {
    id: "vhs",
    label: "VHS",
    category: "post",
    description: "横向抖动、scanline、色偏、dropout 与 tracking bar 的老式录像带效果。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.vhs,
  },
  magnify: {
    id: "magnify",
    label: "Magnify",
    category: "post",
    description: "带像素 HUD、AA、haze 与 chromatic aberration 的放大镜镜头。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.magnify,
  },
  glass: {
    id: "glass",
    label: "Glass",
    category: "post",
    description: "rounded-SDF、rim normal、六波长折射、fresnel 与 GGX 反射的玻璃卡片。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.glass,
  },
  bubble: {
    id: "bubble",
    label: "Bubble",
    category: "post",
    description: "metaball trail ray-march 水滴，保留平滑融合、折射、色散与动态 glints。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.bubble,
  },
  ripple: {
    id: "ripple",
    label: "Ripple",
    category: "post",
    description: "以镜头中心为源的径向涟漪折射扰动，水波式画面。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.ripple,
  },
  "article-highlight": {
    id: "article-highlight",
    label: "Article Highlight",
    category: "post",
    description: "黄色 marker 从左向右划出焦点文字，同时渐进模糊上下信息的 9x9 Gaussian blur。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA["article-highlight"],
  },
  asciify: {
    id: "asciify",
    label: "Asciify",
    category: "post",
    description: "内容按亮度短暂字符化，再严格解码回无像素化的原始画面。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.asciify,
  },
  "retro-dither": {
    id: "retro-dither",
    label: "Retro Dither",
    category: "post",
    description: "Bayer 有序抖动 + 色阶量化的复古像素化效果。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA["retro-dither"],
  },
  displacement: {
    id: "displacement",
    label: "Displacement",
    category: "post",
    description: "以 fBm 域扭曲 UV 的内容扭曲效果。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.displacement,
  },
  droplets: {
    id: "droplets",
    label: "Droplets",
    category: "post",
    description: "CanvasUI 双层下落雨滴场：主滴、连续拖痕、静滴与法线折射。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.droplets,
  },
  frost: {
    id: "frost",
    label: "Frost",
    category: "post",
    description: "霜玻璃模糊 + 冷色调 + 霜晶噪点。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.frost,
  },
  "decrypt-reveal": {
    id: "decrypt-reveal",
    label: "Decrypt Reveal",
    category: "post",
    description: "由 shot 进度驱动的 7-segment 密码字 → 正文单次解锁揭示（文本专属）。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA["decrypt-reveal"],
  },
  "particle-reveal": {
    id: "particle-reveal",
    label: "Particle Reveal",
    category: "post",
    description: "由 shot 进度驱动的粒子汇聚揭示：散射碎片 + 悬浮光点最终无损落入原画面（入场动画）。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA["particle-reveal"],
  },
  "text-focus": {
    id: "text-focus",
    label: "Text Focus",
    category: "post",
    description: "相机拉焦：以可调圆角焦点框锁定目标文字或卡片，背景景深渐进虚化（文本专属）。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA["text-focus"],
  },
  bend: {
    id: "bend",
    label: "Bend",
    category: "transform",
    description: "页面卷曲语义的顶点变形转场。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.bend,
  },
  "store-peel": {
    id: "store-peel",
    label: "Store Peel",
    category: "transform",
    description: "cylinder curl、adhesive back 与贴合翻页弧面的反射光卷页转场。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA["store-peel"],
  },
  cloth: {
    id: "cloth",
    label: "Cloth",
    category: "transform",
    description: "以顶点正弦波动模拟布料起伏的变形转场。",
    consumesMap: true,
    schema: MATERIAL_SCHEMA.cloth,
  },
  clouds: {
    id: "clouds",
    label: "Clouds",
    category: "ambient",
    description: "无历史帧依赖的程序化 fBm 雾场环境。",
    consumesMap: false,
    schema: MATERIAL_SCHEMA.clouds,
  },
  grid: {
    id: "grid",
    label: "Grid",
    category: "ambient",
    description: "持续斜向掠过的程序化编辑网格（纸面/蓝图），细线与主格线保持对齐。",
    consumesMap: false,
    schema: MATERIAL_SCHEMA.grid,
  },
  liquid: {
    id: "liquid",
    label: "Liquid",
    category: "ambient",
    description: "域扭曲 fBm 流动场，双色渐变液面环境。",
    consumesMap: false,
    schema: MATERIAL_SCHEMA.liquid,
  },
  "glyph-rain": {
    id: "glyph-rain",
    label: "Glyph Rain",
    category: "ambient",
    description: "确定性下落字符列（矩阵风）环境。",
    consumesMap: false,
    schema: MATERIAL_SCHEMA["glyph-rain"],
  },
  laser: {
    id: "laser",
    label: "Laser",
    category: "ambient",
    description: "确定性扫描激光线环境氛围。",
    consumesMap: false,
    schema: MATERIAL_SCHEMA.laser,
  },
  blaze: {
    id: "blaze",
    label: "Blaze",
    category: "ambient",
    description: "域扭曲 fBm 火焰/能量场环境。",
    consumesMap: false,
    schema: MATERIAL_SCHEMA.blaze,
  },
  "particle-scroll": {
    id: "particle-scroll",
    label: "Particle Scroll",
    category: "ambient",
    description: "确定性漂浮微粒流环境。",
    consumesMap: false,
    schema: MATERIAL_SCHEMA["particle-scroll"],
  },
};

export const getMaterialDefinition = (id: string) =>
  MATERIAL_REGISTRY[id as MaterialId];
