/**
 * [INPUT]: 依赖同目录的独立 Remotion 模板与内容容器组件
 * [OUTPUT]: 对外提供 `@recut/remotion-kit/templates` 的稳定模板与动态组件导出面
 * [POS]: remotion-templates 的唯一 barrel；预览层通过它按目录 ID 解析真实组件
 * [PROTOCOL]: 变更时更新此头部，然后检查 README.md
 */
export { default as AnimatedList } from "./animated-list";
export { default as AnimatedText } from "./animated-text";
export { default as AreaChart } from "./area-chart";
export { default as BlindsTransition } from "./blinds-transition";
export { default as BokehCircles } from "./bokeh-circles";
export { default as BounceText } from "./bounce-text";
export { default as BubblePopText } from "./bubble-pop-text";
export { default as CameraShake } from "./camera-shake";
export { default as CardFlip } from "./card-flip";
export { default as ChapterTitle } from "./chapter-title";
export { default as ChartAnimation } from "./chart-animation";
export { default as CinematicTitleIntro } from "./cinematic-title-intro";
export { default as CircularProgress } from "./circular-progress";
export { default as ClockWipe } from "./clock-wipe";
export { default as ComparisonChart } from "./comparison-chart";
export { default as CountdownIntro } from "./countdown-intro";
export { default as CountdownTimer } from "./countdown-timer";
export { default as CreditsRoll } from "./credits-roll";
export { default as CrossDissolve } from "./cross-dissolve";
export { default as DonutChart } from "./donut-chart";
export { default as EndCard } from "./end-card";
export { default as FadeThroughBlack } from "./fade-through-black";
export { default as FilmBurn } from "./film-burn";
export { default as FloatingBubbleText } from "./floating-bubble-text";
export { default as GalleryGrid } from "./gallery-grid";
export { default as GeometricPatterns } from "./geometric-patterns";
export { default as GlitchText } from "./glitch-text";
export { default as GradientShift } from "./gradient-shift";
export { default as GridPulse } from "./grid-pulse";
export { default as ImageCarousel } from "./image-carousel";
export { default as ImageComparisonSlider } from "./image-comparison-slider";
export { default as ImageZoomReveal } from "./image-zoom-reveal";
export { default as IrisTransition } from "./iris-transition";
export { default as KenBurns } from "./ken-burns";
export { default as LetterboxReveal } from "./letterbox-reveal";
export { default as LineChart } from "./line-chart";
export { default as LiquidWave } from "./liquid-wave";
export { default as LogoBlurReveal } from "./logo-blur-reveal";
export { default as LogoBounceDrop } from "./logo-bounce-drop";
export { default as LogoFadeReveal } from "./logo-fade-reveal";
export { default as LogoGlitchReveal } from "./logo-glitch-reveal";
export { default as LogoScaleRotate } from "./logo-scale-rotate";
export { default as LogoSpinReveal } from "./logo-spin-reveal";
export { default as LogoSplitReveal } from "./logo-split-reveal";
export { default as LogoStrokeDraw } from "./logo-stroke-draw";
export { default as LogoTypewriter } from "./logo-typewriter";
export { default as LowerThird } from "./lower-third";
export { default as MasonryGallery } from "./masonry-gallery";
export { default as MatrixRain } from "./matrix-rain";
export { default as MorphTransition } from "./morph-transition";
export { default as NoiseGrain } from "./noise-grain";
export { default as NotificationPop } from "./notification-pop";
export { default as ParticleExplosion } from "./particle-explosion";
export { default as ParallaxPan } from "./parallax-pan";
export { default as PhotoStack } from "./photo-stack";
export { default as PictureInPicture } from "./picture-in-picture";
export { default as PieChart } from "./pie-chart";
export { default as PixelTransition } from "./pixel-transition";
export { default as PolaroidFrame } from "./polaroid-frame";
export { default as PoppingText } from "./popping-text";
export { default as ProgressBars } from "./progress-bars";
export { default as ProgressSteps } from "./progress-steps";
export { default as PulsingText } from "./pulsing-text";
export { default as PushTransition } from "./push-transition";
export { default as QuoteCard } from "./quote-card";
export { default as RotatingCarousel } from "./rotating-carousel";
export { default as SlideText } from "./slide-text";
export { default as SlideWipe } from "./slide-wipe";
export { default as SoundWave } from "./sound-wave";
export { default as SplitScreen } from "./split-screen";
export { default as SpotlightReveal } from "./spotlight-reveal";
export { default as Starfield } from "./starfield";
export { default as StatCounter } from "./stat-counter";
export { default as SubscribeReminder } from "./subscribe-reminder";
export { default as TextHighlight } from "./text-highlight";
export { default as TitleSplit } from "./title-split";
export { default as TypewriterSubtitle } from "./typewriter-subtitle";
export { default as VignettePulse } from "./vignette-pulse";
export { default as WhipPan } from "./whip-pan";
export { default as ZoomThrough } from "./zoom-through";
export { default as ZoomPulse } from "./zoom-pulse";

export { Caption } from "./Caption";
export { DigitRoll } from "./DigitRoll";
export { FlashCut } from "./FlashCut";
export { FlameFrame } from "./FlameFrame";
export type { FlameFrameProps } from "./FlameFrame";
export { PageCam } from "./PageCam";
export type { CamKey } from "./PageCam";
export { VerticalTicker } from "./VerticalTicker";
export type { TickerColumn, VerticalTickerProps } from "./VerticalTicker";
